### ISSUE TITLE
Outdated Information Everywhere

### ISSUE THREAD

**Issue by jacobblade700** [ianlamb/stolen-realm-planner#2]
Changes were made to skills that aren't reflected. This is a valuable tool. Please update!

**Comment by DanDuhon** [comment]
This should be fixed, unless you have specific examples.

**Comment by ianlamb** [comment]
Sorry, I don't know why I wasn't notified of this issue. I did do a big update since this was opened, but please let me know if there's any discrepancies still.

**Comment by DanDuhon** [comment]
Being the glutton for punishment that I am, I went through everything.  I guess there is a bunch of stuff that's outdated.  Below is what needs to be updated that I could find.  Hopefully I got at least most of them.  The vast majority of this is going to be in your skills spreadsheet so if that's something you want to add to the repo I could do it myself.

Whoops, the image for Momentum I is mirrored (the toe of the boot is supposed to be facing right).  My bad.

**In effectsGlossary.json:**
- [ ] Salvation: Restores [~100% Spell Power] health per turn.
- [ ] Cripple --> Slow: Movement costs doubled.

Looks like mana cost is currently a number, which is causing mana per turn abilities to show as NaN for mana cost.  I assume this is so you can calculate mana cost at any particular level.  Maybe have a Boolean that denotes mana per turn skills so you can append the " mana per turn" string after the calculation is done?  Affected skills:
- [ ] Aura of Flame
- [ ] Aura of Frost
- [ ] Aura of Lightning
- [ ] Seal of Might
- [ ] Seal of Protection
- [ ] Seal of Salvation
- [ ] Vampiric Aura

_Edit: the above changes are checked into my fork, including manual changes to skills.json for testing._


### The following skills should have Range 7 instead of their current value:
**Fire**
- [ ] Burning Ground
- [ ] Fire Storm
- [ ] Fireball
- [ ] Fireblast
- [ ] Immolate
- [ ] Meteor
- [ ] Meteor Shower

**Lightning**
- [ ] Chain Lightning
- [ ] Dazzling Darts
- [ ] Shocking Shackles
- [ ] Thunder Bolt
- [ ] Thunder Wrath
- [ ] Teleport Other
- [ ] Teleport Self

**Cold**
- [ ] Brain Freeze
- [ ] Deep Freeze
- [ ] Freeze Earth
- [ ] Frost Nova
- [ ] Frost Shard
- [ ] Frozen Spikes
- [ ] Ice Lance
- [ ] Ice Storm
- [ ] Ice Wall
- [ ] Shatter
- [ ] Stasis

**Light**
- [ ] Blinding Light
- [ ] Cure
- [ ] Divine Intervention
- [ ] Elemental Protection
- [ ] Holy Ground
- [ ] Mass Cure
- [ ] Purify
- [ ] Regenerate
- [ ] Shield of Light

**Shadow**
- [ ] Blind
- [ ] Consumption
- [ ] Curse
- [ ] Exorcism
- [ ] Haunt
- [ ] Purge Mana
- [ ] Reaper's Scythe
- [ ] Soul Exchange
- [ ] Soul Fracture
- [ ] Soul Link
- [ ] Spectral Chains

**Thief**
- [ ] Dagger Throw
- [ ] Deadly Dagger
- [ ] Poisoned Dagger
- [ ] Shadow Walk


### Other fixes
**Fire**
- [ ] Cauterize: Cooldown 1
- [ ] Detonate: Range Self
- [ ] Fire Shield: Duration 3
- [ ] Fire Shield: Cooldown 3
- [ ] Fissure: Range 6
- [ ] Hot Head I: Increase all damage and healing by 8%.
- [ ] Hot Head II: Increase all damage and healing by an additional 12%.

**Lightning**
- [ ] Enchant Lightning: Range 5
- [ ] Energy Cannon: Range 6
- [ ] Lightning Shield: Duration 3
- [ ] Lightning Shield: Cooldown 3
- [ ] Overload: Duration 1
- [ ] Shocking Shackles: Duration 1
- [ ] Storm Brewing: Each stack of Shocked you've applied increases your Critical Hit Chance by 1%.
- [ ] Thunder Struck: Your lightning damage has a 10% chance to conjure a thunderbolt on a random enemy dealing [~110% Spell Power] lightning damage within 2 hexes of its blast.
- [ ] Twister: Range 6

**Cold**
- [ ] Break the Ice: The first time you use a damaging or healing skill in battle, its effectiveness is increased by 100%.
- [ ] Breath of Winter: Range 4
- [ ] Frost Armor: Duration 3
- [ ] Frost Armor: Cooldown 3
- [ ] Frostbite (tier 4 passive) should be named Frozen Core
- [ ] Invulnerable Winter: Every stack of Chilled applied increases your Armor and Magic Armor by 12.

**Warrior**
- [ ] Crushing Slam: Range 5
- [ ] Dispelling Fracture: Deals [~100% Attack Power] weapon damage, removes 1 random beneficial status from the target, and lowers the target's Resistance by 20% for 2 turns.
- [ ] Fracture: Deals [~70% Attack Power] weapon damage. Lowers the target's Resistance by 20% for 2 turns.
- [ ] Furious George: Might increases the effectiveness of Armor and Magic Armor by 1% per point.
- [ ] Life Cleave: Swing in a 180 degree arc striking all foes for [~150% Attack Power] weapon damage. Heals you for 100% of the damage dealt.
- [ ] Mortal Fracture: Deals [~100% Attack Power] weapon damage and lowers target's Resistance by 20% and Healing received by 50% for 2 turns.
- [ ] Slam: Range 5
- [ ] Slam: Blast Radius Special
- [ ] Stunning Slam: Range 5
- [ ] Sunder: Deals [~200% Attack Power] weapon damage. Ignores all armor and resists. Cannot be dodged. Heal for 100% of the damage caused.
- [ ] Vitality Break: Cooldown 1

**Light**
- [ ] Light's Beckon: Range 50
- [ ] Shield of Retribution: Conjures a shield imbued with holy flame absorbing [200% Spell Power] damage. Upon shield depletion, it explodes and deals [200% Spell Power] fire damage to all foes in a 1 hex radius.

**Ranger**
- [ ] Animal Companion Grizzly: Cooldown 5
- [ ] Bleeding Shot: Range 8
- [ ] Branching Shot: Range 8
- [ ] Branching Shot: Deals [~200% Attack Power] weapon damage. Bounces to enemies within 3 hexes. Each bounce increases its damage by 50%.
- [ ] Bounty Hunter's Mark: Range 8
- [ ] Called Shot: Range 10
- [ ] Called Shot: Cooldown 3
- [ ] Called Shot: Deals [~100% Attack Power] weapon damage. Every hex between you and your target increases the damage by 10%.  Called Shot cannot be dodged or blocked.
- [ ] Crippling Shot: Range 8
- [ ] Dispelling Shot: Range 8
- [ ] Impaling Shot: Range 8
- [ ] Impaling Shot: Deals [~300% Attack Power] weapon damage in a line. Each enemy it pierces increases its damage by 100%.
- [ ] Long Shot: Range 10
- [ ] Long Shot: Deals [~100% Attack Power] weapon damage. Every hex between you and your target increases the damage by 10%.
- [ ] Mythic Reach: All ranged abilities get an additional 5 hex range.
- [ ] Pinning Shot: Range 8
- [ ] Relocate: Range 7
- [ ] Sniper Shot: Range 12
- [ ] Sniper Shot: Cooldown 4
- [ ] Sniper Shot: Deals [~100% Attack Power] weapon damage. Every hex between you and your target increases the damage by 15%.
- [ ] Stalker's Mark: Range 8
- [ ] Summon Raven: Cooldown 3
- [ ] Tracker's Mark: Range 8

**Shadow**
- [ ] Consumption: Devour the life force of all enemies within 2 hexes dealing [~100% Spell Power] shadow damage and reducing enemy Maximum Health by 10% and giving you 10% Increased Damage for each enemy affected.
- [ ] Dark Ritual: Range 6
- [ ] Exorcism: Deals [~150% Spell Power] shadow damage and removes a random beneficial status from the target. If a status is removed, the target suffers an additional [~150% Spell Power] shadow damage.
- [ ] Leech Dexterity: Damage caused steals [level * 0.2] points of Dexterity. Lasts the entire battle. Stacks up to 10 times.
- [ ] Leech Intelligence: Damage caused steals [level * 0.2] points of Intelligence. Lasts the entire battle. Stacks up to 10 times.
- [ ] Leech Might: Damage caused steals [level * 0.2] points of Might. Lasts the entire battle. Stacks up to 10 times.
- [ ] Purge Mana: Removes 15% of the target's max mana and restores 15% of the caster's max mana.
- [ ] Spectral Chains: Deals [~80% Spell Power] shadow damage and applies Immobilized for 1 turn.

**Thief**
- [ ] Cripple: Deals [~70% Attack Power] weapon damage. Applies Slow for 1 turn.
- [ ] En Garde: Increases your maximum amount of Counter Attacks per turn by 2.
- [ ] Gouge: Deals [~70% Attack Power] weapon damage.  Applies Slow and Blind for 1 turn.
- [ ] Shadow Walk: Teleport through the shadows. Applies Stealth for this turn. Unaffected by increased range modifiers.
- [ ] Smoke Bomb (yours is more descriptive - not sure if you did that or the new description is simply less descriptive.  If it was yours feel free to keep it.): Increases Dodge Chance by 50% for all characters in smoke.

**Monk**
- [ ] Pain Suppression: AP Cost None
- [ ] Pain Suppression: Range Self
- [ ] Pain Suppression: Mana Cost 13
- [ ] Pain Suppression: Cooldown 3
- [ ] Sweeping Kick: Blast Radius 1
- [ ] Sweeping Kick (this doesn't exactly match what's in game, but in game is using the older Cripple status rather than the newer Slow status.): Deal [~160% Attack Power] physical damage to all enemies within 1 hex. Knocks back all enemies up to 3 hexes. Applies Slow for 1 turn.
- [ ] Meditation: Mana Cost 0
- [ ] Cyclone Kick (same deal with Sweeping Kick, though this one needed the damage updated too): Deals [~160% Attack Power] damage. Pulls enemies within 4 hexes towards you. Targets are Slow for 1 turn.

**Comment by ianlamb** [comment]
Wow, thanks for compiling that! 🙏

@DanDuhon if you're interested in getting access to the data sheet, send me a message on Discord (`ehtypical`) and I can walk you through how it works and give you edit access. Otherwise, I'll try to get to these updates when I have some time.

**Comment by DanDuhon** [comment]
This should be fixed now. I think anything further should be in a new issue so we don't make this more messy than it is.

**Comment by ianlamb** [comment]
Agreed, and thanks again for your help @DanDuhon
